# Generated by Django 3.2.3 on 2023-11-04 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231104_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимый символ', regex='^[\\w.@+-]+$')], verbose_name='Slug'),
        ),
    ]
